apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: av-webstack-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/AndreiVlaicu8172/linux.git
    targetRevision: main
    path: k8s/stack

  destination:
    server: https://kubernetes.default.svc
    namespace: av

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
